### ISSUE TITLE
Prevent danger of committing temporary database.yml entries to git

### ISSUE THREAD

**Issue by A5308Y** [rmehner/uff_db_loader#24]
Idea:
```yaml
development:
  << : *shared
  database: <%= UffDbLoader.current_database_name || 'act_development' %>
```

where `UffDbLoader.current_database_name` reads a file in `tmp` that `UffDbLoader` changes after pulling a dump.

Changes `database.yml` like described above with script or message if it fails.

**Comment by A5308Y** [comment]
Idea:
```yaml
development:
  << : *shared
  database: <%= UffDbLoader.current_database_name || 'act_development' %>
```
