### ISSUE TITLE
🐞 Wrong environment found during installation

### ISSUE THREAD

**Issue by rmehner** [rmehner/uff_db_loader#49]
Given the following contents of `database.yml`:

```yml
# common settings for all connections, you can overwrite those in the
# specific environment settings
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  port: 3306
  username: root
  password: ""

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  password: test

staging:
  <<: *default
  password: test
```

running `bin/rails uff_db_loader:install` will detect the environments wrong and result in this initializer:

```rb
# frozen_string_literal: true

# Check out our README: https://github.com/rmehner/uff_db_loader/blob/main/README.md

if defined?(UffDbLoader)
  UffDbLoader.configure do |config|
    config.ssh_user = 'SSH_USER'
    config.ssh_host = 'HOST_OF_YOUR_SITE'
    config.db_name = 'YOUR_DATABASE_NAME'
    config.db_system = :mysql # Possible values are :postgresql and :mysql
    config.environments = ["default", "production", "staging"]

    # Optional settings:
    # config.app_name = 'my_app' # Defaults to the Rails app name
    # config.dumps_directory = '/path/to/dumps' # Defaults to Rails.root.join('dumps')
    # config.database_config_file = 'path/to/database.yml' # Defaults to Rails.root.join('config', 'database.yml')
  end
end
```

`default` is not a valid environment tho.
